language: node_js
node_js:
  - "14"
services:
  - redis-server
  - postgresql
env:
  global:
    - DB_NAME=poster
    - DB_USER=adam
install:
  - yarn
cache:
  directories:
    - node_modules
before_script:
  - psql --command="CREATE USER ${DB_USER};"
  - psql --command="CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"
  - psql --dbname=$DB_NAME --file=postgres/queries.sql
script:
  - nohup yarn start &
  - sleep 3
  - yarn test
