version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    build: ./postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  poster-api:
    container_name: backend
    build: .
    env_file:
      - .env
    command: npm start
    working_dir: /usr/src/poster-api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
      - postgres