version: "3.8"
services:
  redis:
    image: redis:6.0.8-alpine
    ports:
      - "6379:6379"
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  poster-api:
    build: .
    command: npx nodemon server.js
    volumes:
      - .:/srv/poster-api
      - poster-api_node_modules:/srv/poster-api/node_modules
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
      - postgres
volumes:
  poster-api_node_modules:
